import type { DoughScalingInput, FormulaWarning, Ingredient, PizzaDoughInput, StarterFeedingInput, StarterSplit } from '@/types/baking';
export type Warn = FormulaWarning;
export type { Ingredient } from '@/types/baking';
export const round = (value: number, digits = 1) => Math.round(value * 10 ** digits) / 10 ** digits;
export const pct = (value: number) => `${round(value)}%`;
export const grams = (value: number) => `${Math.round(value)} g`;
function assertPositive(name: string, value: number) { if (!Number.isFinite(value) || value <= 0) throw new Error(`${name} must be greater than zero.`); }
function splitStarter(starterWeightGrams: number, starterHydrationPct: number): StarterSplit { assertPositive('starter hydration', starterHydrationPct); const flourGrams = starterWeightGrams / (1 + starterHydrationPct / 100); return { flourGrams, waterGrams: starterWeightGrams - flourGrams, hydrationPct: starterHydrationPct }; }
function warnings(hydrationPct: number, saltPct: number, starterPct = 0): Warn[] { const out: Warn[] = []; if (hydrationPct < 55) out.push({ code: 'low-hydration', message: 'Hydration is low; expect a stiffer dough.' }); if (hydrationPct > 85) out.push({ code: 'high-hydration', message: 'Hydration is high; expect a wetter dough.' }); if (saltPct > 3) out.push({ code: 'high-salt', message: 'Salt percentage is high for most bread formulas.' }); if (starterPct > 40) out.push({ code: 'high-starter', message: 'Starter percentage is high; fermentation may move quickly.' }); return out; }
export function calculateBakersPercentage(input: { flourWeightGrams: number; hydrationPct: number; starterPct: number; saltPct: number; oilPct?: number; sugarPct?: number; customIngredients?: { name: string; percentage?: number; weightGrams?: number }[] }) {
  assertPositive('flour', input.flourWeightGrams); const flour = input.flourWeightGrams; const items: Ingredient[] = [
    { name: 'Flour', weightGrams: flour, bakerPercentage: 100, note: 'Baseline' },
    { name: 'Water', weightGrams: flour * input.hydrationPct / 100, bakerPercentage: input.hydrationPct, note: 'Added water' },
    { name: 'Starter', weightGrams: flour * input.starterPct / 100, bakerPercentage: input.starterPct, note: 'Total starter weight' },
    { name: 'Salt', weightGrams: flour * input.saltPct / 100, bakerPercentage: input.saltPct, note: 'Salt' }
  ];
  if (input.oilPct) items.push({ name: 'Oil', weightGrams: flour * input.oilPct / 100, bakerPercentage: input.oilPct, note: 'Optional' });
  if (input.sugarPct) items.push({ name: 'Sugar', weightGrams: flour * input.sugarPct / 100, bakerPercentage: input.sugarPct, note: 'Optional' });
  (input.customIngredients ?? []).forEach((i) => { const p = i.percentage ?? ((i.weightGrams ?? 0) / flour * 100); if (p > 0) items.push({ name: i.name || 'Custom ingredient', weightGrams: flour * p / 100, bakerPercentage: p, note: 'Custom' }); });
  return { ingredients: items, totalDoughWeightGrams: items.reduce((sum, i) => sum + i.weightGrams, 0), totalFormulaPct: items.reduce((sum, i) => sum + (i.bakerPercentage ?? 0), 0), warnings: warnings(input.hydrationPct, input.saltPct, input.starterPct) };
}
export function calculateBakersPercentagesFromWeights(input: { flourWeightGrams: number; waterWeightGrams: number; starterWeightGrams: number; saltWeightGrams: number; oilWeightGrams?: number; sugarWeightGrams?: number; customIngredients?: { name: string; weightGrams?: number }[] }) {
  assertPositive('flour', input.flourWeightGrams); const flour = input.flourWeightGrams; const add = (name: string, weightGrams: number, note: string): Ingredient => ({ name, weightGrams, bakerPercentage: weightGrams / flour * 100, note });
  const items = [add('Flour', flour, 'Baseline'), add('Water', input.waterWeightGrams, 'Added water'), add('Starter', input.starterWeightGrams, 'Total starter weight'), add('Salt', input.saltWeightGrams, 'Salt')];
  if (input.oilWeightGrams) items.push(add('Oil', input.oilWeightGrams, 'Optional'));
  if (input.sugarWeightGrams) items.push(add('Sugar', input.sugarWeightGrams, 'Optional'));
  (input.customIngredients ?? []).forEach((i) => { if ((i.weightGrams ?? 0) > 0) items.push(add(i.name || 'Custom ingredient', i.weightGrams ?? 0, 'Custom')); });
  return { ingredients: items, totalDoughWeightGrams: items.reduce((s, i) => s + i.weightGrams, 0), totalFormulaPct: items.reduce((s, i) => s + (i.bakerPercentage ?? 0), 0), warnings: warnings(input.waterWeightGrams / flour * 100, input.saltWeightGrams / flour * 100, input.starterWeightGrams / flour * 100) };
}
export function calculateSourdoughHydration(input: { mainFlourGrams: number; addedWaterGrams: number; starterWeightGrams: number; starterHydrationPct: number; saltWeightGrams: number }) {
  assertPositive('main flour', input.mainFlourGrams); const starterSplit = splitStarter(input.starterWeightGrams, input.starterHydrationPct); const totalFlourGrams = input.mainFlourGrams + starterSplit.flourGrams; const totalWaterGrams = input.addedWaterGrams + starterSplit.waterGrams; const totalHydrationPct = totalWaterGrams / totalFlourGrams * 100; const items: Ingredient[] = [{ name: 'Main flour', weightGrams: input.mainFlourGrams, bakerPercentage: 100, note: 'Added flour' }, { name: 'Added water', weightGrams: input.addedWaterGrams, bakerPercentage: input.addedWaterGrams / input.mainFlourGrams * 100, note: 'Added water' }, { name: 'Starter', weightGrams: input.starterWeightGrams, bakerPercentage: input.starterWeightGrams / input.mainFlourGrams * 100, note: 'Split into flour and water' }, { name: 'Salt', weightGrams: input.saltWeightGrams, bakerPercentage: input.saltWeightGrams / input.mainFlourGrams * 100, note: 'Salt' }]; return { ingredients: items, starterSplit, totalFlourGrams, totalWaterGrams, starterFlourGrams: starterSplit.flourGrams, starterWaterGrams: starterSplit.waterGrams, totalHydrationPct, totalDoughWeightGrams: items.reduce((s, i) => s + i.weightGrams, 0), warnings: warnings(totalHydrationPct, input.saltWeightGrams / input.mainFlourGrams * 100) };
}
export function calculateStarterFeeding(input: StarterFeedingInput) { assertPositive('target starter', input.targetStarterWeightGrams); assertPositive('seed part', input.seedPart); assertPositive('flour part', input.flourPart); assertPositive('water part', input.waterPart); const total = input.targetStarterWeightGrams + (input.extraGrams ?? 0); const part = total / (input.seedPart + input.flourPart + input.waterPart); const seedStarterGrams = part * input.seedPart; const feedingFlourGrams = part * input.flourPart; const feedingWaterGrams = part * input.waterPart; const hydration = input.waterPart / input.flourPart * 100; const items: Ingredient[] = [{ name: 'Seed starter', weightGrams: seedStarterGrams, note: 'Existing starter' }, { name: 'Flour', weightGrams: feedingFlourGrams, note: 'Feeding flour' }, { name: 'Water', weightGrams: feedingWaterGrams, note: 'Feeding water' }]; return { ingredients: items, totalNeededStarterGrams: total, finalStarterWeightGrams: input.targetStarterWeightGrams, retainedExtraStarterGrams: input.extraGrams ?? 0, seedStarterGrams, feedingFlourGrams, feedingWaterGrams, totalHydrationPct: hydration, warnings: [] as Warn[] };
}
function flourFromTarget(target: number, hydrationPct: number, starterPct: number, saltPct: number, oilPct = 0, sugarPct = 0, yeastPct = 0, starterHydrationPct = 100) { const starterFlourRatio = (starterPct / 100) / (1 + starterHydrationPct / 100); const starterWaterRatio = (starterPct / 100) - starterFlourRatio; return target / (1 + hydrationPct / 100 + saltPct / 100 + oilPct / 100 + sugarPct / 100 + yeastPct / 100); }
export function calculateDoughScaling(input: DoughScalingInput) { const flour = input.mode === 'by-flour-weight' ? (input.flourWeightGrams ?? 0) : flourFromTarget(input.targetDoughWeightGrams ?? 0, input.hydrationPct, input.starterPct, input.saltPct, input.oilPct, input.sugarPct, input.yeastPct, input.starterHydrationPct); const result = calculateBakersPercentage({ flourWeightGrams: flour, hydrationPct: input.hydrationPct, starterPct: input.starterPct, saltPct: input.saltPct, oilPct: input.oilPct, sugarPct: input.sugarPct }); const starterSplit = splitStarter(flour * input.starterPct / 100, input.starterHydrationPct); const perUnit = result.ingredients.map((i) => ({ ...i, weightGrams: i.weightGrams / input.loafCount })); return { ...result, perUnit, starterSplit, starterFlourGrams: starterSplit.flourGrams, starterWaterGrams: starterSplit.waterGrams, totalFlourGrams: flour + starterSplit.flourGrams, totalWaterGrams: flour * input.hydrationPct / 100 + starterSplit.waterGrams, totalHydrationPct: (flour * input.hydrationPct / 100 + starterSplit.waterGrams) / (flour + starterSplit.flourGrams) * 100 };
}
export function calculatePizzaDough(input: PizzaDoughInput) { const target = input.pizzaCount * input.ballWeightGrams; const flour = flourFromTarget(target, input.hydrationPct, input.starterPct ?? 0, input.saltPct, input.oilPct, input.sugarPct, input.leaveningType === 'yeast' ? (input.yeastPct ?? 0) : 0, input.starterHydrationPct ?? 100); const result = calculateBakersPercentage({ flourWeightGrams: flour, hydrationPct: input.hydrationPct, starterPct: input.leaveningType === 'sourdough' ? (input.starterPct ?? 0) : 0, saltPct: input.saltPct, oilPct: input.oilPct, sugarPct: input.sugarPct }); const yeast = input.leaveningType === 'yeast' ? { name: 'Yeast', weightGrams: flour * (input.yeastPct ?? 0) / 100, bakerPercentage: input.yeastPct ?? 0, note: 'Yeast' } : undefined; const ingredients = yeast ? [...result.ingredients, yeast] : result.ingredients; const totalDoughWeightGrams = ingredients.reduce((s, i) => s + i.weightGrams, 0); const perUnit = ingredients.map((i) => ({ ...i, weightGrams: i.weightGrams / input.pizzaCount })); return { ...result, ingredients, perUnit, totalDoughWeightGrams, warnings: warnings(input.hydrationPct, input.saltPct, input.starterPct ?? 0) };
}
