export type Warn={code:string;message:string;severity:'info'|'warning'|'error'};
export type Ingredient={name:string;weightGrams:number;bakerPercentage?:number;note?:string};
const pos=(v:number,n:string)=>{if(!Number.isFinite(v)||v<=0)throw new Error(`${n} must be greater than 0.`)};
const nonneg=(v:number,n:string)=>{if(!Number.isFinite(v)||v<0)throw new Error(`${n} must be 0 or greater.`)};
const w=(code:string,message:string,severity:Warn['severity']='warning'):Warn=>({code,message,severity});
export const round=(v:number,d=1)=>Math.round((v+Number.EPSILON)*10**d)/10**d;
export const grams=(v:number)=>`${round(v,v<10?1:0)} g`;
export const pct=(v:number)=>`${round(v,1)}%`;
export function bakerPercentage(ingredientWeightGrams:number,totalFlourWeightGrams:number){nonneg(ingredientWeightGrams,'Ingredient weight');pos(totalFlourWeightGrams,'Total flour weight');return ingredientWeightGrams/totalFlourWeightGrams*100;}
export function weightFromBakerPercentage(flourWeightGrams:number,percentage:number){pos(flourWeightGrams,'Flour weight');nonneg(percentage,"Baker's percentage");return flourWeightGrams*percentage/100;}
export function splitStarterByHydration(starterWeightGrams:number,starterHydrationPct:number){nonneg(starterWeightGrams,'Starter weight');pos(starterHydrationPct,'Starter hydration');const flourGrams=starterWeightGrams/(1+starterHydrationPct/100);return{starterWeightGrams,flourGrams,waterGrams:starterWeightGrams-flourGrams,hydrationPct:starterHydrationPct};}
export function baseFlourFromTargetDoughWeight(p:{targetDoughWeightGrams:number;hydrationPct:number;starterPct?:number;saltPct?:number;oilPct?:number;sugarPct?:number;yeastPct?:number}){pos(p.targetDoughWeightGrams,'Target dough weight');pos(p.hydrationPct,'Hydration');const total=100+p.hydrationPct+(p.starterPct??0)+(p.saltPct??0)+(p.oilPct??0)+(p.sugarPct??0)+(p.yeastPct??0);return p.targetDoughWeightGrams/(total/100);}
const warns=(hyd:number,salt=0,starter=0,sh=100,total=0,ball=0)=>{const a:Warn[]=[];if(hyd<40)a.push(w('low-hydration','This is a very stiff dough. Check whether the hydration value is intended.'));if(hyd>100)a.push(w('high-hydration','This is a very high-hydration dough and may be difficult to handle.'));if(salt>4)a.push(w('high-salt','Salt above 4% is unusually high for most bread formulas.'));if(starter>60)a.push(w('high-starter','A high starter percentage can speed fermentation significantly.'));if(sh!==100)a.push(w('custom-starter-hydration','Starter has been split using your custom hydration setting.','info'));if(total>10000)a.push(w('large-batch','Large batch. Check scale capacity and mixing method.'));if(ball&&ball<120)a.push(w('small-pizza-ball','This is a small dough ball. Check pizza size.'));if(ball&&ball>500)a.push(w('large-pizza-ball','This is a large dough ball. Check pizza size and style.'));return a;};
const ing=(name:string,weight:number,base:number,note=''):Ingredient=>({name,weightGrams:weight,bakerPercentage:bakerPercentage(weight,base),note});
export function calculateBakersPercentage(i:{flourWeightGrams:number;hydrationPct:number;starterPct:number;saltPct:number;oilPct?:number;sugarPct?:number}){pos(i.flourWeightGrams,'Flour weight');const f=i.flourWeightGrams,water=weightFromBakerPercentage(f,i.hydrationPct),starter=weightFromBakerPercentage(f,i.starterPct),salt=weightFromBakerPercentage(f,i.saltPct),oil=weightFromBakerPercentage(f,i.oilPct??0),sugar=weightFromBakerPercentage(f,i.sugarPct??0);const ingredients=[ing('Flour',f,f,'Always 100%'),ing('Water',water,f),ing('Starter',starter,f,'Starter is treated as total ingredient.'),ing('Salt',salt,f)];if(oil)ingredients.push(ing('Oil',oil,f));if(sugar)ingredients.push(ing('Sugar',sugar,f));return{ingredients,totalDoughWeightGrams:ingredients.reduce((s,x)=>s+x.weightGrams,0),waterGrams:water,starterWeightGrams:starter,saltGrams:salt,warnings:warns(i.hydrationPct,i.saltPct,i.starterPct)}}
export function calculateSourdoughHydration(i:{mainFlourGrams:number;addedWaterGrams:number;starterWeightGrams:number;starterHydrationPct:number;saltWeightGrams:number}){pos(i.mainFlourGrams,'Main flour');const sp=splitStarterByHydration(i.starterWeightGrams,i.starterHydrationPct),totalFlour=i.mainFlourGrams+sp.flourGrams,totalWater=i.addedWaterGrams+sp.waterGrams,added=bakerPercentage(i.addedWaterGrams,i.mainFlourGrams),total=bakerPercentage(totalWater,totalFlour),saltPct=bakerPercentage(i.saltWeightGrams,totalFlour);return{starterSplit:sp,totalFlourGrams:totalFlour,totalWaterGrams:totalWater,addedHydrationPct:added,totalHydrationPct:total,saltPct,totalDoughWeightGrams:i.mainFlourGrams+i.addedWaterGrams+i.starterWeightGrams+i.saltWeightGrams,ingredients:[ing('Main flour',i.mainFlourGrams,totalFlour),ing('Added water',i.addedWaterGrams,totalFlour),ing('Starter',i.starterWeightGrams,totalFlour,`${round(sp.flourGrams)}g flour + ${round(sp.waterGrams)}g water`),ing('Salt',i.saltWeightGrams,totalFlour)],warnings:warns(total,saltPct,0,i.starterHydrationPct)}}
export function calculateDoughScaling(i:{mode:'by-flour-weight'|'by-target-dough-weight';flourWeightGrams?:number;targetDoughWeightGrams?:number;loafCount:number;hydrationPct:number;starterPct:number;starterHydrationPct:number;saltPct:number;oilPct?:number;sugarPct?:number}){pos(i.loafCount,'Loaf count');const f=i.mode==='by-target-dough-weight'?baseFlourFromTargetDoughWeight({targetDoughWeightGrams:i.targetDoughWeightGrams??0,hydrationPct:i.hydrationPct,starterPct:i.starterPct,saltPct:i.saltPct,oilPct:i.oilPct,sugarPct:i.sugarPct}):(i.flourWeightGrams??0);pos(f,'Flour weight');const water=weightFromBakerPercentage(f,i.hydrationPct),starter=weightFromBakerPercentage(f,i.starterPct),salt=weightFromBakerPercentage(f,i.saltPct),oil=weightFromBakerPercentage(f,i.oilPct??0),sugar=weightFromBakerPercentage(f,i.sugarPct??0),sp=splitStarterByHydration(starter,i.starterHydrationPct);const ingredients=[ing('Flour',f,f),ing('Added water',water,f),ing('Starter',starter,f,`${round(sp.flourGrams)}g flour + ${round(sp.waterGrams)}g water`),ing('Salt',salt,f)];if(oil)ingredients.push(ing('Oil',oil,f));if(sugar)ingredients.push(ing('Sugar',sugar,f));const total=ingredients.reduce((s,x)=>s+x.weightGrams,0),totalFlour=f+sp.flourGrams,totalWater=water+sp.waterGrams;return{ingredients,perUnit:ingredients.map(x=>({...x,weightGrams:x.weightGrams/i.loafCount})),totalDoughWeightGrams:total,perLoafWeightGrams:total/i.loafCount,totalFlourGrams:totalFlour,totalWaterGrams:totalWater,addedHydrationPct:bakerPercentage(water,f),totalHydrationPct:bakerPercentage(totalWater,totalFlour),warnings:warns(i.hydrationPct,i.saltPct,i.starterPct,i.starterHydrationPct,total)}}
export function calculateStarterFeeding(i:{targetStarterWeightGrams:number;seedPart:number;flourPart:number;waterPart:number;extraGrams?:number}){pos(i.targetStarterWeightGrams,'Target starter weight');pos(i.seedPart,'Seed part');pos(i.flourPart,'Flour part');pos(i.waterPart,'Water part');const total=i.targetStarterWeightGrams+(i.extraGrams??0),parts=i.seedPart+i.flourPart+i.waterPart,seed=total*i.seedPart/parts,flour=total*i.flourPart/parts,water=total*i.waterPart/parts;return{seedStarterGrams:seed,feedingFlourGrams:flour,feedingWaterGrams:water,totalNeededStarterGrams:total,ingredients:[{name:'Seed starter',weightGrams:seed,note:'Existing mature starter.'},{name:'Flour',weightGrams:flour,note:'Fresh flour.'},{name:'Water',weightGrams:water,note:'Water for feeding.'}],warnings:i.extraGrams?[w('extra','Feed includes retained extra starter.','info')]:[]}}
export function calculatePizzaDough(i:{pizzaCount:number;ballWeightGrams:number;hydrationPct:number;saltPct:number;oilPct?:number;sugarPct?:number;yeastPct?:number;starterPct?:number;starterHydrationPct?:number;leaveningType:'yeast'|'sourdough'}){pos(i.pizzaCount,'Pizza count');const target=i.pizzaCount*i.ballWeightGrams,lev=i.leaveningType==='yeast'?(i.yeastPct??0):(i.starterPct??0),f=baseFlourFromTargetDoughWeight({targetDoughWeightGrams:target,hydrationPct:i.hydrationPct,saltPct:i.saltPct,oilPct:i.oilPct,sugarPct:i.sugarPct,yeastPct:i.leaveningType==='yeast'?lev:0,starterPct:i.leaveningType==='sourdough'?lev:0}),water=weightFromBakerPercentage(f,i.hydrationPct),salt=weightFromBakerPercentage(f,i.saltPct),oil=weightFromBakerPercentage(f,i.oilPct??0),sugar=weightFromBakerPercentage(f,i.sugarPct??0),yeast=i.leaveningType==='yeast'?weightFromBakerPercentage(f,lev):0,starter=i.leaveningType==='sourdough'?weightFromBakerPercentage(f,lev):0;const ingredients=[ing('Flour',f,f),ing('Water',water,f),ing('Salt',salt,f)];if(oil)ingredients.push(ing('Oil',oil,f));if(sugar)ingredients.push(ing('Sugar',sugar,f));if(yeast)ingredients.push(ing('Yeast',yeast,f));let totalHyd=i.hydrationPct;if(starter){const sp=splitStarterByHydration(starter,i.starterHydrationPct??100);ingredients.push(ing('Starter',starter,f,`${round(sp.flourGrams)}g flour + ${round(sp.waterGrams)}g water`));totalHyd=bakerPercentage(water+sp.waterGrams,f+sp.flourGrams)}return{ingredients,perUnit:ingredients.map(x=>({...x,weightGrams:x.weightGrams/i.pizzaCount})),totalDoughWeightGrams:target,perBallWeightGrams:i.ballWeightGrams,totalHydrationPct:totalHyd,warnings:warns(i.hydrationPct,i.saltPct,i.starterPct??0,i.starterHydrationPct??100,target,i.ballWeightGrams)}}
