export type GuidePage = { slug: string; title: string; description: string; h1: string; canonicalPath: string; intro: string; sections: { heading: string; body: string[] }[]; related: { href: string; label: string }[] };
export const guidePages: GuidePage[] = [
  { slug: 'bakers-percentage', title: "Baker's Percentage Guide | DoughMath", description: "Learn how baker's percentage works and why flour is always treated as 100%.", h1: "How Baker's Percentage Works", canonicalPath: '/guides/bakers-percentage', intro: "Baker's percentage is the scaling system behind repeatable bread formulas.", sections: [{ heading: 'Core idea', body: ['Total flour is always 100%.', 'Every other ingredient is measured as a percentage of total flour weight.', 'This lets a formula scale from one loaf to many loaves without changing the ratio.'] }, { heading: 'Example', body: ['If flour is 500g and water is 375g, hydration is 75%.', 'If salt is 10g, salt is 2%.'] }], related: [{ href: '/bakers-percentage-calculator', label: "Baker's Percentage Calculator" }, { href: '/grams-to-bakers-percentage', label: 'Grams to Baker’s Percentage' }] },
  { slug: 'total-hydration-vs-added-hydration', title: 'Total Hydration vs Added Hydration | DoughMath', description: 'Understand the difference between added hydration and total hydration when sourdough starter is included.', h1: 'Total Hydration vs Added Hydration', canonicalPath: '/guides/total-hydration-vs-added-hydration', intro: 'Sourdough formulas can look wetter or drier depending on whether starter flour and water are included.', sections: [{ heading: 'Added hydration', body: ['Added hydration uses only added water divided by main flour.', 'It is useful when following a simple recipe written without preferment math.'] }, { heading: 'Total hydration', body: ['Total hydration adds starter flour to total flour and starter water to total water.', 'This is the more accurate number for comparing sourdough formulas.'] }], related: [{ href: '/sourdough-hydration-calculator', label: 'Sourdough Hydration Calculator' }, { href: '/total-hydration-calculator', label: 'Total Hydration Calculator' }] },
  { slug: 'sourdough-starter-feeding-ratios', title: 'Sourdough Starter Feeding Ratios Guide | DoughMath', description: 'Learn what 1:1:1, 1:2:2, 1:5:5, and 1:10:10 starter feedings mean by weight.', h1: 'Sourdough Starter Feeding Ratios', canonicalPath: '/guides/sourdough-starter-feeding-ratios', intro: 'Starter feeding ratios are weight ratios for seed starter, flour, and water.', sections: [{ heading: 'Reading a ratio', body: ['1:2:2 means one part seed starter, two parts flour, and two parts water.', 'A 100g target at 1:2:2 has five total parts, so one part is 20g.'] }, { heading: 'Choosing ratios', body: ['Higher feedings such as 1:5:5 or 1:10:10 use less seed starter relative to fresh food.', 'DoughMath calculates weights only and does not predict peak time.'] }], related: [{ href: '/starter-feeding-calculator', label: 'Starter Feeding Calculator' }, { href: '/sourdough-starter-ratio-1-5-5', label: '1:5:5 Starter Feeding' }] },
  { slug: 'how-to-scale-bread-recipes', title: 'How to Scale Bread Recipes | DoughMath', description: 'Learn how to scale bread recipes by flour weight, target dough weight, and loaf count.', h1: 'How to Scale Bread Recipes', canonicalPath: '/guides/how-to-scale-bread-recipes', intro: 'Scaling bread is easiest when the recipe is expressed with baker percentages.', sections: [{ heading: 'Scale from flour weight', body: ['Use known flour weight when you already know how much flour you want to use.', 'Water, starter, salt, and optional ingredients are calculated from flour.'] }, { heading: 'Scale from target dough weight', body: ['Use target dough weight when you need a specific loaf or batch size.', 'For sourdough, starter flour and water should be included in total flour and total water.'] }], related: [{ href: '/dough-scaling-calculator', label: 'Dough Scaling Calculator' }, { href: '/bread-recipe-scaler', label: 'Bread Recipe Scaler' }] },
  { slug: 'why-use-grams-for-bread-baking', title: 'Why Use Grams for Bread Baking | DoughMath', description: 'Why grams are more reliable than cups for bread, sourdough, and pizza dough formulas.', h1: 'Why Use Grams for Bread Baking', canonicalPath: '/guides/why-use-grams-for-bread-baking', intro: 'Bread formulas depend on ratios, and ratios depend on accurate weight.', sections: [{ heading: 'Cups vary', body: ['A cup of flour can weigh very different amounts depending on the flour type and packing.', 'Small differences become large when scaling dough.'] }, { heading: 'Grams repeat', body: ['A gram is a direct weight measurement.', 'Using grams makes hydration, salt percentage, and starter percentage easier to compare.'] }], related: [{ href: '/bakers-percentage-calculator', label: "Baker's Percentage Calculator" }, { href: '/pizza-dough-calculator', label: 'Pizza Dough Calculator' }] }
];
export const guidePaths = guidePages.map((page) => ({ canonicalPath: page.canonicalPath, priority: 0.55, changeFrequency: 'monthly' as const }));
export const getGuidePage = (slug: string) => guidePages.find((page) => page.slug === slug);
