import type { CalculatorType } from '@/types/baking';
export interface ToolPageData { slug: string; title: string; description: string; h1: string; calculatorType: CalculatorType; canonicalPath: string; defaultInputs: Record<string, number | string>; intro: string; formulaNotes: string[]; examples: { title: string; input: string; output: string }[]; faqs: { question: string; answer: string }[]; relatedSlugs: string[]; priority: number; isLongTail?: boolean }
export const BASE_URL = 'https://doughmath.ymirtool.com';
const p = (slug: string, title: string, description: string, h1: string, calculatorType: CalculatorType, defaultInputs: Record<string, number | string>, relatedSlugs: string[], priority = 0.85, isLongTail = false): ToolPageData => ({ slug, title: `${title} | DoughMath`, description, h1, calculatorType, canonicalPath: `/${slug}`, defaultInputs, intro: description, formulaNotes: ['All calculations use grams internally.', 'Display values are rounded only for readability.', 'The calculator runs locally in your browser.'], examples: [{ title: 'Example', input: 'Enter the default values shown in the calculator.', output: 'The result table shows ingredient weights and baker percentages.' }], faqs: [{ question: 'Does this save my recipe?', answer: 'No. Calculations run in your browser without accounts or uploads.' }, { question: 'Can I share the result?', answer: 'Yes. Use the share URL button to copy calculator state.' }], relatedSlugs, priority, isLongTail });
export const toolPages: ToolPageData[] = [
  p('bakers-percentage-calculator', "Baker's Percentage Calculator", "Calculate baker's percentages and ingredient weights from flour, hydration, starter, salt, oil, and sugar in grams.", "Baker's Percentage Calculator", 'bakers-percentage', { flour: 500, hyd: 75, starter: 20, salt: 2, oil: 0, sugar: 0, bakerMode: 'percentages' }, ['grams-to-bakers-percentage','bakers-percentage-to-grams','sourdough-hydration-calculator'], .9),
  p('sourdough-hydration-calculator', 'Sourdough Hydration Calculator', 'Split starter into flour and water, then calculate added hydration, total hydration, salt percentage, and dough weight.', 'Sourdough Hydration Calculator', 'sourdough-hydration', { flour: 500, water: 350, starter: 100, sh: 100, saltg: 10 }, ['total-hydration-calculator','bakers-percentage-calculator','starter-feeding-calculator'], .9),
  p('starter-feeding-calculator', 'Starter Feeding Calculator', 'Calculate seed starter, flour, and water for common or custom sourdough starter feeding ratios.', 'Starter Feeding Calculator', 'starter-feeding', { target: 100, seed: 1, flourpart: 2, waterpart: 2, extra: 0 }, ['sourdough-starter-ratio-1-2-2','sourdough-starter-ratio-1-5-5','levain-calculator'], .85),
  p('dough-scaling-calculator', 'Dough Scaling Calculator', 'Scale bread dough from target dough weight, flour weight, loaf count, hydration, starter percentage, and salt percentage.', 'Dough Scaling Calculator', 'dough-scaling', { mode: 'target', target: 1500, flour: 500, loaves: 2, hyd: 75, starter: 20, sh: 100, salt: 2, oil: 0, sugar: 0, yeast: 0 }, ['bread-recipe-scaler','dough-weight-calculator','sourdough-hydration-calculator'], .95),
  p('pizza-dough-calculator', 'Pizza Dough Calculator', 'Calculate flour, water, salt, oil, yeast or starter, total dough weight, and per-ball weights for pizza dough.', 'Pizza Dough Calculator', 'pizza-dough', { count: 3, ball: 280, hyd: 65, salt: 2.5, oil: 2, sugar: 0, yeast: 0.2, starter: 20, sh: 100, lev: 'yeast' }, ['pizza-dough-ball-weight-calculator','sourdough-pizza-calculator','dough-scaling-calculator'], .9),
  p('total-hydration-calculator', 'Total Hydration Calculator', 'Calculate total dough hydration including starter flour and starter water.', 'Total Hydration Calculator', 'sourdough-hydration', { flour: 600, water: 420, starter: 150, sh: 100, saltg: 12 }, ['sourdough-hydration-calculator','dough-scaling-calculator'], .72, true),
  p('sourdough-starter-ratio-1-2-2', '1:2:2 Starter Feeding Calculator', 'Preset starter feeding calculator for a 1:2:2 sourdough starter ratio.', '1:2:2 Starter Feeding Calculator', 'starter-feeding', { target: 150, seed: 1, flourpart: 2, waterpart: 2, extra: 0 }, ['starter-feeding-calculator','sourdough-starter-ratio-1-5-5'], .7, true),
  p('sourdough-starter-ratio-1-5-5', '1:5:5 Starter Feeding Calculator', 'Preset starter feeding calculator for a 1:5:5 sourdough starter ratio.', '1:5:5 Starter Feeding Calculator', 'starter-feeding', { target: 220, seed: 1, flourpart: 5, waterpart: 5, extra: 0 }, ['starter-feeding-calculator','sourdough-starter-ratio-1-2-2'], .7, true),
  p('levain-calculator', 'Levain Calculator', 'Calculate levain build weights using starter feeding ratios.', 'Levain Calculator', 'starter-feeding', { target: 180, seed: 1, flourpart: 3, waterpart: 3, extra: 0 }, ['starter-feeding-calculator','sourdough-hydration-calculator'], .72, true),
  p('bread-recipe-scaler', 'Bread Recipe Scaler', 'Scale a bread formula by target dough weight or flour weight.', 'Bread Recipe Scaler', 'dough-scaling', { mode: 'flour', flour: 800, loaves: 2, hyd: 72, starter: 20, sh: 100, salt: 2, oil: 0, sugar: 0, yeast: 0 }, ['dough-scaling-calculator','dough-weight-calculator'], .72, true),
  p('dough-weight-calculator', 'Dough Weight Calculator', 'Calculate total dough weight and per-loaf dough weight from a bread formula.', 'Dough Weight Calculator', 'dough-scaling', { mode: 'target', target: 1000, loaves: 1, hyd: 70, starter: 20, sh: 100, salt: 2, oil: 0, sugar: 0, yeast: 0 }, ['dough-scaling-calculator','bread-recipe-scaler'], .72, true),
  p('pizza-dough-ball-weight-calculator', 'Pizza Dough Ball Weight Calculator', 'Calculate pizza dough ingredients by ball weight and number of pizzas.', 'Pizza Dough Ball Weight Calculator', 'pizza-dough', { count: 4, ball: 250, hyd: 65, salt: 2.5, oil: 2, sugar: 0, yeast: 0.2, starter: 20, sh: 100, lev: 'yeast' }, ['pizza-dough-calculator','sourdough-pizza-calculator'], .72, true),
  p('sourdough-pizza-calculator', 'Sourdough Pizza Calculator', 'Calculate sourdough pizza dough using starter percentage and starter hydration.', 'Sourdough Pizza Calculator', 'pizza-dough', { count: 3, ball: 280, hyd: 65, salt: 2.5, oil: 2, sugar: 0, starter: 20, sh: 100, lev: 'sourdough', yeast: 0 }, ['pizza-dough-calculator','sourdough-hydration-calculator'], .72, true),
  p('grams-to-bakers-percentage', 'Grams to Baker’s Percentage Calculator', 'Convert ingredient gram weights into baker’s percentages.', 'Grams to Baker’s Percentage Calculator', 'bakers-percentage', { bakerMode: 'weights', flour: 1000, bpWater: 700, bpStarter: 0, bpSalt: 20, bpOil: 0, bpSugar: 0 }, ['bakers-percentage-calculator','bakers-percentage-to-grams'], .72, true),
  p('bakers-percentage-to-grams', 'Baker’s Percentage to Grams Calculator', 'Convert baker percentages into gram ingredient weights.', 'Baker’s Percentage to Grams Calculator', 'bakers-percentage', { bakerMode: 'percentages', flour: 1000, hyd: 70, starter: 0, salt: 2, oil: 0, sugar: 0 }, ['bakers-percentage-calculator','grams-to-bakers-percentage'], .72, true)
];
export const legalPages = [{ slug: 'about', title: 'About DoughMath', description: 'About the DoughMath bread and sourdough calculator site.', canonicalPath: '/about', priority: 0.5 }, { slug: 'privacy', title: 'Privacy Policy', description: 'Privacy policy for DoughMath browser-only calculators.', canonicalPath: '/privacy', priority: 0.5 }, { slug: 'terms', title: 'Terms of Use', description: 'Terms of use for DoughMath.', canonicalPath: '/terms', priority: 0.4 }, { slug: 'disclaimer', title: 'Disclaimer', description: 'Baking calculation disclaimer for DoughMath.', canonicalPath: '/disclaimer', priority: 0.5 }] as const;
export const allPages = [{ canonicalPath: '/', priority: 1, changeFrequency: 'weekly' as const }, ...toolPages.map((page) => ({ canonicalPath: page.canonicalPath, priority: page.priority, changeFrequency: page.isLongTail ? 'monthly' as const : 'weekly' as const })), ...legalPages.map((page) => ({ canonicalPath: page.canonicalPath, priority: page.priority, changeFrequency: 'yearly' as const }))];
export const longTailPages = toolPages.filter((page) => page.isLongTail);
export function getToolPage(slug: string) { return toolPages.find((page) => page.slug === slug); }
export function getToolPageOrThrow(slug: string) { const page = getToolPage(slug); if (!page) throw new Error(`Unknown tool page: ${slug}`); return page; }
