import type {Metadata} from 'next';
import {notFound} from 'next/navigation';
import {Suspense} from 'react';
import Calculator from '@/components/Calculator';
const titles:Record<string,string>={'bakers-percentage-calculator':"Baker's Percentage Calculator",'sourdough-hydration-calculator':'Sourdough Hydration Calculator','starter-feeding-calculator':'Starter Feeding Calculator','dough-scaling-calculator':'Dough Scaling Calculator','pizza-dough-calculator':'Pizza Dough Calculator'};
const legal:Record<string,[string,string]>={about:['About DoughMath','DoughMath is a free browser-only calculator site for bread, sourdough, starter feeding, dough scaling, and pizza dough formulas. It is not a recipe library, AI recipe generator, baking journal, fermentation predictor, nutrition calculator, or cloud recipe storage product.'],privacy:['Privacy Policy','DoughMath calculators run in your browser. The site does not require an account, does not upload recipe inputs, and does not store recipes in a cloud database. Share URLs may contain calculator values in the query string.'],disclaimer:['Disclaimer','DoughMath provides formula calculations for home baking. It does not guarantee baking outcomes, fermentation timing, starter activity, oven behavior, food safety, or professional culinary results.']};
export function generateStaticParams(){return [...Object.keys(titles),...Object.keys(legal)].map(slug=>({slug}))}
export function generateMetadata({params}:{params:{slug:string}}):Metadata{const name=titles[params.slug]??legal[params.slug]?.[0];return name?{title:`${name} | DoughMath`,description:`${name} for local bread and sourdough calculations.`,alternates:{canonical:`/${params.slug}`},openGraph:{title:`${name} | DoughMath`,description:'Browser-only baking calculator.',type:'website'}}:{}}
export default function Page({params}:{params:{slug:string}}){if(legal[params.slug])return <main className="mx-auto max-w-3xl px-4 py-12"><h1 className="text-4xl font-bold">{legal[params.slug][0]}</h1><p className="mt-6 leading-7 text-stone-700">{legal[params.slug][1]}</p></main>;const name=titles[params.slug];if(!name)notFound();return <main className="mx-auto max-w-6xl px-4 py-10"><section className="mx-auto max-w-3xl text-center"><h1 className="text-4xl font-bold tracking-tight sm:text-5xl">{name}</h1><p className="mt-4 text-lg text-stone-600">Calculate grams-first baking formulas locally in your browser. Copy results, print a recipe card, and restore state from the URL.</p><p className="mt-2 text-sm text-stone-500">No login, no upload, no cloud recipe storage.</p></section><div className="mt-8"><Suspense fallback={<p>Loading calculator…</p>}><Calculator slug={params.slug}/></Suspense></div><section className="no-print mt-10 rounded-2xl border bg-white p-6"><h2 className="text-2xl font-semibold">Formula notes</h2><p className="mt-3 text-stone-600">Flour is the 100% basis in baker's math. Starter hydration is split into flour and water for total hydration calculators. This MVP uses starter total weight percentage, not prefermented flour percentage.</p><h2 className="mt-6 text-2xl font-semibold">Common mistakes</h2><ul className="mt-3 list-disc pl-5 text-stone-600"><li>Do not confuse added hydration with total hydration.</li><li>Do not treat 100% hydration starter as 100% water.</li><li>Use grams for repeatable results; cups vary by flour type.</li></ul><h2 className="mt-6 text-2xl font-semibold">FAQ</h2><p className="mt-3 text-stone-600">All calculator inputs are local. Share URLs store only core input values in the query string.</p></section></main>}
